<a href="https://colab.research.google.com/github/AttiqueAnwar/00_TensorFlow-Fundamental/blob/main/00_tensorflow_fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the most fundamentals of tensors using tensorflow.

More Specifically


1.   Intro to tensors
2.   Getting info from tensors
3.   Manipulating Tensors
4.   Tensors & NumPy
5.   Using @tf.func
6.   Using GPU with TensorFLow
7.   Exercises to try yourself




# Introduction to Tensors

In [ ]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor (ndim is no of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of our vector
vector.ndim

1

In [ ]:
#create a matrix having more than 1 dimensions
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#matrix dimension
matrix.ndim

2

In [ ]:
scalar = tf.constant([7])
scalar

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([7], dtype=int32)>

In [ ]:
#another matrix
another_matrix = tf.constant ([[10. , 5.],
                               [4. , 3.],
                               [6. , 2.]], dtype=tf.float16 ) #specify the datatype by dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 4.,  3.],
       [ 6.,  2.]], dtype=float16)>

In [ ]:
#Whats the number of dimensions in another_matrix
another_matrix.ndim

2

In [ ]:
#lets create a tensor
tensor = tf.constant ([[[10,2,3],
                        [3,2,6]],
                       [[55,3,23],
                        [11,22,22]],
                        [[42,21,21],
                         [21,44,12]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  2,  3],
        [ 3,  2,  6]],

       [[55,  3, 23],
        [11, 22, 22]],

       [[42, 21, 21],
        [21, 44, 12]]], dtype=int32)>

In [ ]:
#dimension tensor
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (eg. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a Vector)


### Creating Tensors with tf.Variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
#Create the same tensor with tf.Variable same as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lets try the change in one of elements in changable tensor
#changeable_tensor[0]     --shows 10
changeable_tensor[0] = 7
changeable_tensor         #would give error

TypeError: ignored

In [ ]:
#When we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#Trying changes in unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor       #constant causes it to give error

AttributeError: ignored

### Creating Random Tensors
Random Tensors are tensors of some arbitrary size which contains random numbers