<a href="https://colab.research.google.com/github/AttiqueAnwar/00_TensorFlow-Fundamental/blob/main/00_tensorflow_fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the most fundamentals of tensors using tensorflow.

More Specifically


1.   Intro to tensors
2.   Getting info from tensors
3.   Manipulating Tensors
4.   Tensors & NumPy
5.   Using @tf.func
6.   Using GPU with TensorFLow
7.   Exercises to try yourself




# Introduction to Tensors

In [1]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the number of dimensions of a tensor (ndim is no of dimensions)
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the dimension of our vector
vector.ndim

1

In [6]:
#create a matrix having more than 1 dimensions
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
#matrix dimension
matrix.ndim

2

In [8]:
scalar = tf.constant([7])
scalar

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([7], dtype=int32)>

In [9]:
#another matrix
another_matrix = tf.constant ([[10. , 5.],
                               [4. , 3.],
                               [6. , 2.]], dtype=tf.float16 ) #specify the datatype by dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 4.,  3.],
       [ 6.,  2.]], dtype=float16)>

In [10]:
#Whats the number of dimensions in another_matrix
another_matrix.ndim

2

In [11]:
#lets create a tensor
tensor = tf.constant ([[[10,2,3],
                        [3,2,6]],
                       [[55,3,23],
                        [11,22,22]],
                        [[42,21,21],
                         [21,44,12]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  2,  3],
        [ 3,  2,  6]],

       [[55,  3, 23],
        [11, 22, 22]],

       [[42, 21, 21],
        [21, 44, 12]]], dtype=int32)>

In [12]:
#dimension tensor
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (eg. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a Vector)


### Creating Tensors with tf.Variable

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
#Create the same tensor with tf.Variable same as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
#lets try the change in one of elements in changable tensor
#changeable_tensor[0]     --shows 10
changeable_tensor[0] = 7
changeable_tensor         #would give error

TypeError: ignored

In [16]:
#When we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
#Trying changes in unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor       #constant causes it to give error

AttributeError: ignored

### Creating Random Tensors
Random Tensors are tensors of some arbitrary size which contains random numbers

In [ ]:
#create two random(but same) tensors
random_1 = tf.random.Generator.from_seed(42)   #set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

#are they equal?
random_1, random_2, random_1==random_2

### Shuffle the order of elements in a tensor

In [18]:
#Shuffle a tensor (valuable for when we want to shuffle our data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10 , 7],
                           [3 , 4],
                           [7 , 1]])

#shuffle our non shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 7,  1]], dtype=int32)>

In [19]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 7,  1]], dtype=int32)>

If we want our shuffled tensor in same order then we use Global level seed and operational seed both.
> Rule 4 : "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [20]:
tf.random.set_seed(42)      #global level random seed
tf.random.shuffle(not_shuffled, seed=42)      #operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 7,  1]], dtype=int32)>

###Other Ways to make Tensors


In [21]:
## Create a tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
#Create a tensor of zeros
tf.zeros([4,3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [23]:
#Create a tensor of zeros with shape
tf.zeros(shape= (4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

  The main difference between NumPy arrays and Tensors is that tensors can be run on GPU (much faster as numerical computing).

In [24]:
#Turning NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)     #create a NumPy array between 1 and 24
numpy_A

# X = tf.constant(some_matrix)    #capital for matrix
# y = tf.constant(vector)         #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [25]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [26]:
# Change the shape of numpy_A
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [27]:
A.ndim

3

In [28]:
B.ndim

1

In [29]:
# Change the shape of numpy_A
A = tf.constant(numpy_A, shape=(6,4))
A

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [30]:
A.ndim

2

## Getting information from tensors

When dealing with the tensors we probably need to know about the following attributes:
* Shape
* Rank
* Size
* Axis or dimension

In [45]:
#Create a tensor of rank 4
rank_4_tensor = tf.zeros (shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [33]:
rank_4_tensor.ndim , rank_4_tensor.shape, tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [46]:
#Get various attributes of tensor
print("Datatype of every element: " , rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along 0 axis:" , rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in tensor: " , tf.size(rank_4_tensor))
print("Total number of elements in tensor: " , tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis:  5
Total number of elements in tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor:  120


## Indexing Tensors
Tensors can be indexed just like Pythons Lists

In [39]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [50]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2 , :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>